export default Object.freeze({
  HOME: { route: "Home", label: "Home" },
  LOGIN: { route: "LoginScreen", label: "LoginScreen" },
  CURRENT_BOOKING: { route: "CurrentBooking", label: "Current Booking" },
  CREATE_BOOKING: { route: "CreateBooking", label: "Create Inventory" },
  CREATE_BOOKING_N: { route: "CreateBookingNavigator", label: "CreateBookingNavigator" },
  VEHICLE_INVENTORY: { route: "VehicleInventory", label: "Vehicle Inventory" },
  DASHBOARD: { route: "Dashboard", label: "Dashboard" },
  DROP: { route: "Drop", label: "Drop" },
  PICKUP: { route: "Pickup", label: "Pickup" },
  HISTORY: { route: "History", label: "History" },
  TODAYSDROP: { route: "TodaysDrop", label: "Today's Drop" },
  FUTUREDROP: { route: "FutureDrop", label: "Future Drop" },
  EXTENDEDDROP: { route: "ExtendedDrop", label: "Extended Drop" },
  TODAYS_PICKUP: { route: "TodaysPickup", label: "Today's Pickup" },
  FUTURE_PICKUP: { route: "FuturePickup", label: "Future Pickup" },
  OVERDUE_PICKUP: { route: "OverDuePickup", label: "Overdue Pickup" },
  ALLBIKES: { route: "AllBikesList", label: "All Bikes List" },
  RENTCOLLECTION: { route: "RentCollection", label: "Rent Collection" },
  ADDBIKES: { route: "AddBikes", label: "Add Bikes" },
  RENT_CALCULATOR: { route: "RentCalculator", label: "Rent Calculator" },
  AVAILABLE: { route: "Available", label: "Available" },
  ON_BOOKING: { route: "OnBooking", label: "On Booking" },
  MAINTENANCE: { route: "Maintenance", label: "Maintenance" },
  MOBILENO_INPUT_SCREEN: { route: "MobileInputScreen", label: "MobileInputScreen" },
  CREATEBOOKINGPAYSCREEN: { route: "CreateBookingPayScreen", label: "CreateBookingPayScreen" },
  CHECKIN_SCREEN: { route: "CheckInScreen", label: "CheckInScreen" },
  DOCUMENT_UPLOAD_SCREEN: { route: "DocumentUploadScreen", label: "DocumentUploadScreen" },
  CAMERA_SCREEN: { route: "OpenCameraScreen", label: "OpenCameraScreen" },
  CUSTOMERS_DETAILS_SCREEN: { route: "RiderDetailsScreen", label: "RiderDetailsScreen" },
  DIFFERENT_RIDER_SCREEN: { route: "DifferentRiderScreen", label: "DifferentRiderScreen" },
  VEHICLE_PHOTOS_SCREEN: { route: "VehiclePhotosScreen", label: "VehiclePhotosScreen" },
  VERIFY_DOCUMENTS_SCREEN1: { route: "VerifyDocuments1", label: "VerifyDocuments1" },
  VERIFY_DOCUMENTS_SCREEN2: { route: "VerifyDocuments2", label: "VerifyDocuments2" },
  OTP_COMPONENT_SCREEN: { route: "OtpComponentScreen", label: "OtpComponentScreen" },
  SIGNUP_COMPONENT_SCREEN: { route: "SignUpComponentScreen", label: "SignUpComponentScreen" },
  SOP_SCREEN: { route: "SOPScreen", label: "SOPScreen" },
  REPORTS_SCREEN: { route: "ReportsScreen", label: "ReportsScreen" },
});
